### ISSUE TITLE
Missing requirements.txt in PyPI package

### ISSUE THREAD

**Issue by rubeon** [bitlabstudio/django-tinylinks#9]
Hi, there

thanks for your Django contribution here. 

Installing with `pip` on Ubuntu 16.04 currently fails with the following:

```bash
$ pip install django-tinylinks
Collecting django-tinylinks
  Downloading django-tinylinks-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LqjD9L/django-tinylinks/setup.py", line 6, in <module>
        install_requires = open('requirements.txt').read().splitlines()
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

Looking inside the package, `requirements.txt` does indeed seem to be missing.

Thanks,
Eric

**Comment by Tyrdall** [comment]
@rubeon Fixed! Please try v0.7.1
